// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Course struct {
	ID               int64          `json:"id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Language         sql.NullString `json:"language"`
	GradingScale     sql.NullString `json:"grading_scale"`
	Organiser        sql.NullString `json:"organiser"`
	LearningOutcomes sql.NullString `json:"learning_outcomes"`
	Prerequisites    sql.NullString `json:"prerequisites"`
	TeacherName      sql.NullString `json:"teacher_name"`
	TeacherEmail     sql.NullString `json:"teacher_email"`
	CourseLink       sql.NullString `json:"course_link"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be positive or negative
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Recommendation struct {
	ID           int64           `json:"id"`
	UserUsername string          `json:"user_username"`
	TranscriptID sql.NullInt64   `json:"transcript_id"`
	Summary      sql.NullString  `json:"summary"`
	Payload      json.RawMessage `json:"payload"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Summary struct {
	ID               int64     `json:"id"`
	UserUsername     string    `json:"user_username"`
	RecommendationID int64     `json:"recommendation_id"`
	PdfPath          string    `json:"pdf_path"`
	CreatedAt        time.Time `json:"created_at"`
}

type Transcript struct {
	ID            int64          `json:"id"`
	UserUsername  string         `json:"user_username"`
	FilePath      string         `json:"file_path"`
	TextExtracted sql.NullString `json:"text_extracted"`
	Meta          []byte         `json:"meta"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
