// db/sqlc/querier.go

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (Recommendation, error)
	CreateScholarship(ctx context.Context, arg CreateScholarshipParams) (Scholarship, error)
	CreateSummary(ctx context.Context, arg CreateSummaryParams) (Summary, error)
	CreateTranscript(ctx context.Context, arg CreateTranscriptParams) (Transcript, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteScholarship(ctx context.Context, arg DeleteScholarshipParams) error
	DeleteSummary(ctx context.Context, arg DeleteSummaryParams) error
	GetRecommendation(ctx context.Context, id int64) (Recommendation, error)
	GetSummary(ctx context.Context, arg GetSummaryParams) (Summary, error)
	GetTranscript(ctx context.Context, id int64) (Transcript, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAllCourses(ctx context.Context) ([]Course, error)
	ListCourses(ctx context.Context, limit int64) ([]Course, error)
	ListRecentScholarshipsByUser(ctx context.Context, arg ListRecentScholarshipsByUserParams) ([]Scholarship, error)
	ListRecommendations(ctx context.Context, userUsername string) ([]ListRecommendationsRow, error)
	ListScholarshipsByUser(ctx context.Context, userUsername string) ([]Scholarship, error)
	ListSummaries(ctx context.Context, userUsername string) ([]Summary, error)
	ListTranscripts(ctx context.Context, userUsername string) ([]ListTranscriptsRow, error)
}

var _ Querier = (*Queries)(nil)
