// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (Recommendation, error)
	CreateSummary(ctx context.Context, arg CreateSummaryParams) (Summary, error)
	CreateTranscript(ctx context.Context, arg CreateTranscriptParams) (Transcript, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSummary(ctx context.Context, id int64) error
	GetRecommendation(ctx context.Context, id int64) (Recommendation, error)
	GetSummary(ctx context.Context, id int64) (Summary, error)
	GetTranscript(ctx context.Context, id int64) (Transcript, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAllCourses(ctx context.Context) ([]Course, error)
	ListCourses(ctx context.Context, limit int64) ([]Course, error)
	ListRecommendations(ctx context.Context, userUsername string) ([]ListRecommendationsRow, error)
	ListSummaries(ctx context.Context, userUsername string) ([]Summary, error)
	ListTranscripts(ctx context.Context, userUsername string) ([]ListTranscriptsRow, error)
}

var _ Querier = (*Queries)(nil)
