// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summary.sql

package db

import (
	"context"
)

const createSummary = `-- name: CreateSummary :one
INSERT INTO summaries (
  user_username, recommendation_id, pdf_path
) VALUES ($1, $2, $3)
RETURNING id, user_username, recommendation_id, pdf_path, created_at
`

type CreateSummaryParams struct {
	UserUsername     string `json:"user_username"`
	RecommendationID int64  `json:"recommendation_id"`
	PdfPath          string `json:"pdf_path"`
}

func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) (Summary, error) {
	row := q.db.QueryRowContext(ctx, createSummary, arg.UserUsername, arg.RecommendationID, arg.PdfPath)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.RecommendationID,
		&i.PdfPath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSummary = `-- name: DeleteSummary :exec
DELETE FROM summaries WHERE id = $1
`

func (q *Queries) DeleteSummary(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSummary, id)
	return err
}

const getSummary = `-- name: GetSummary :one
SELECT id, user_username, recommendation_id, pdf_path, created_at FROM summaries WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSummary(ctx context.Context, id int64) (Summary, error) {
	row := q.db.QueryRowContext(ctx, getSummary, id)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.UserUsername,
		&i.RecommendationID,
		&i.PdfPath,
		&i.CreatedAt,
	)
	return i, err
}

const listSummaries = `-- name: ListSummaries :many
SELECT id, user_username, recommendation_id, pdf_path, created_at FROM summaries
WHERE user_username = $1
ORDER BY id DESC
`

func (q *Queries) ListSummaries(ctx context.Context, userUsername string) ([]Summary, error) {
	rows, err := q.db.QueryContext(ctx, listSummaries, userUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Summary{}
	for rows.Next() {
		var i Summary
		if err := rows.Scan(
			&i.ID,
			&i.UserUsername,
			&i.RecommendationID,
			&i.PdfPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
